const jobData = [
    {
      job_Id: '2034837',
      title: 'Chuyên Viên Quản Trị Mạng',
      company_name: 'SmartSign',
      district_name: 'Quận 1, Hồ Chí Minh',
      image: 'https://salt.topdev.vn/NGLxp8f0_RSOe1g-ts9l1fFKSNCJJG0-WFjl7o3To5k/fit/384/1000/ce/1/aHR0cHM6Ly9hc3NldHMudG9wZGV2LnZuL2ltYWdlcy8yMDIwLzExLzA5L2NoLWt5LXMtdmluYS12aW5hY2EtbG9nby5wbmc',
      description: 'Quản trị các thiết bị mạng như switch, Router, Firewall, thiết bị cân bằng tải...',
      salary_from: 15000000,
      salary_to: 25000000,
      salary: '15000000 VND to 25000000 VND',
      requirement: 'Quản lý hệ thống máy chủ Linux (CentOS), Windows...',
      companyId: '2034837',
      expire_on: 'undetermined',
      ref_job_Id: '2034837',
      ref_link: 'https://topdev.vn/detail-jobs/chuyen-vien-quan-tri-mang-smartsign-2034837',
      address_name: '41A Nguyễn Phi Khanh, Phường Tân Định, Quận 1, Thành phố Hồ Chí Minh',
      benefit: 'Lương thỏa thuận tùy theo kinh nghiệm...',
      experience: 'From 1 year',
      job_level: ['Junior', 'Middle'],
      job_type: ['Fulltime'],
      work_at: ['In Office'],
      tech_stack: ['.NET', 'Cisco', 'IPS/IDS'],
      job_industry: 'Phần Mềm',
    },
    {
      job_Id: '2034838',
      title: 'Frontend Developer',
      company_name: 'CodeWave',
      district_name: 'Quận 3, Hồ Chí Minh',
      image: 'https://salt.topdev.vn/ZDltt4RvsmGEZlvbNtqp0TFNg3zIFihFOOzCcNk31MU/fit/256/1000/ce/1/aHR0cHM6Ly9hc3NldHMudG9wZGV2LnZuL2ltYWdlcy8yMDIzLzA3LzI2L1RvcERldi1sb2dvLUNKLU9saXZlbmV0d29ya3MtVklOQS0oMSktMTY5MDM0NDc4My5wbmc',
      description: 'Thiết kế và phát triển giao diện người dùng...',
      salary_from: 20000000,
      salary_to: 30000000,
      salary: '20000000 VND to 30000000 VND',
      requirement: 'Thành thạo React.js hoặc Angular...',
      companyId: '2034838',
      expire_on: '2024-12-01',
      ref_job_Id: '2034838',
      ref_link: 'https://topdev.vn/detail-jobs/frontend-developer-codewave-2034838',
      address_name: '12 Pasteur, Quận 3, Thành phố Hồ Chí Minh',
      benefit: 'Lương cạnh tranh, môi trường làm việc năng động...',
      experience: 'From 2 years',
      job_level: ['Middle', 'Senior'],
      job_type: ['Fulltime'],
      work_at: ['Hybrid'],
      tech_stack: ['React.js', 'HTML', 'CSS'],
      job_industry: 'Công Nghệ',
    },
    // Thêm 8 mục dữ liệu tương tự với nội dung thay đổi theo vị trí công việc
  ];
  
  export default jobData;
  